### ISSUE TITLE
unknown keys

### ISSUE THREAD

**Issue by chovy** [tedconf/node-m3u8#15]
```
Handling value: 233200  for unknown key: average-bandwidth
Handling value: 398200  for unknown key: average-bandwidth
Handling value: 605000  for unknown key: average-bandwidth
Handling value: 840400  for unknown key: average-bandwidth
Handling value: 1317800  for unknown key: average-bandwidth
Handling value: 2233000  for unknown key: average-bandwidth
Handling value: 3520000  for unknown key: average-bandwidth
Handling value: 5500000  for unknown key: average-bandwidth
Handling value: "CC1"  for unknown key: instream-id
Handling value: "cc"  for unknown key: closed-captions
Handling value: "cc"  for unknown key: closed-captions
Handling value: "cc"  for unknown key: closed-captions
Handling value: "cc"  for unknown key: closed-captions
Handling value: 30.000  for unknown key: frame-rate
Handling value: 398585  for unknown key: average-bandwidth
Handling value: 30.000  for unknown key: frame-rate
Handling value: 682203  for unknown key: average-bandwidth
Handling value: 30.000  for unknown key: frame-rate
Handling value: 1200819  for unknown key: average-bandwidth
Handling value: 30.000  for unknown key: frame-rate
Handling value: 2537877  for unknown key: average-bandwidth
Handling value: 15.000  for unknown key: frame-rate
Handling value: 114966  for unknown key: average-bandwidth
Handling value: 30.000  for unknown key: frame-rate
Handling value: 220310  for unknown key: average-bandwidth
```

**Comment by chovy** [comment]
Getting more:

```
Handling value: 30.000  for unknown key: frame-rate
Handling value: 421474  for unknown key: average-bandwidth
Handling value: 30.000  for unknown key: frame-rate
Handling value: 717880  for unknown key: average-bandwidth
Handling value: 30.000  for unknown key: frame-rate
Handling value: 1239691  for unknown key: average-bandwidth
Handling value: 30.000  for unknown key: frame-rate
Handling value: 2587579  for unknown key: average-bandwidth
Handling value: 15.000  for unknown key: frame-rate
Handling value: 124385  for unknown key: average-bandwidth
Handling value: 30.000  for unknown key: frame-rate
Handling value: 237905  for unknown key: average-bandwidth
Handling value: "CC1"  for unknown key: instream-id
Handling value: "cc"  for unknown key: closed-captions
Handling value: "cc"  for unknown key: closed-captions
Handling value: "cc"  for unknown key: closed-captions
Handling value: "cc"  for unknown key: closed-captions
Handling value: 233200  for unknown key: average-bandwidth
Handling value: 398200  for unknown key: average-bandwidth
Handling value: 605000  for unknown key: average-bandwidth
Handling value: 840400  for unknown key: average-bandwidth
Handling value: 1317800  for unknown key: average-bandwidth
Handling value: 2233000  for unknown key: average-bandwidth
Handling value: 3520000  for unknown key: average-bandwidth
Handling value: 5500000  for unknown key: average-bandwidth
```

**Comment by chovy** [comment]
```
Handling value: "CC1"  for unknown key: instream-id
Handling value: "captions"  for unknown key: closed-captions
Handling value: "captions"  for unknown key: closed-captions
Handling value: "captions"  for unknown key: closed-captions
Handling value: "captions"  for unknown key: closed-captions
Handling value: "captions"  for unknown key: closed-captions
```

**Comment by chovy** [comment]
can we get rid of these please? They are rather obnoxious to see in the output.

**Comment by chovy** [comment]
Hey guys, if anyone is using this I fixed these warnings in a fork: https://github.com/chovy/node-m3u8

**Comment by konsumer** [comment]
@chovy I am still getting these warnings, and you have issues disabled on your repo:

```
Handling value: "2"  for unknown key: channels
Handling value: "2"  for unknown key: channels
Handling value: "2"  for unknown key: channels
Handling value: 636239  for unknown key: _avg-bandwidth
Handling value: 669206  for unknown key: _avg-bandwidth
Handling value: 399448  for unknown key: _avg-bandwidth
Handling value: 432415  for unknown key: _avg-bandwidth
Handling value: 817231  for unknown key: _avg-bandwidth
Handling value: 850198  for unknown key: _avg-bandwidth
Handling value: 1128868  for unknown key: _avg-bandwidth
Handling value: 1161835  for unknown key: _avg-bandwidth
Handling value: 1749919  for unknown key: _avg-bandwidth
Handling value: 1850765  for unknown key: _avg-bandwidth
Handling value: 2312184  for unknown key: _avg-bandwidth
Handling value: 2413030  for unknown key: _avg-bandwidth
Handling value: 3313665  for unknown key: _avg-bandwidth
Handling value: 3414511  for unknown key: _avg-bandwidth
```

Maybe just a `quiet` option to not output the warnings?

**Comment by chovy** [comment]
I think when you fork a repo issues are disabled. Your getting different keys than me in that error.

**Comment by chovy** [comment]
I've updated and released my module.
